//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public int QId { get; set; }
        public Nullable<int> CorrectOption { get; set; }
        public string ComprehensiveAnswer { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
