//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportCard
    {
        public int ReportId { get; set; }
        public System.Guid TestId { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public int Paperid { get; set; }
        public int LevelId { get; set; }
        public int TotalScore { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public bool IsRevaluate { get; set; }
    }
}
