//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scores
    {
        public System.Guid TestId { get; set; }
        public int ScoreId { get; set; }
        public int UserId { get; set; }
        public int Score { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public int QId { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    }
}
